### ISSUE TITLE
No more jsonpatch format for extensions ? 

### ISSUE THREAD

**Issue by mpostelnicu** [open-contracting/ocds_bid_extension#1]
Hi @timgdavies 
Sorry probably you guys discussed this inside some of the tickets here but probably i missed it. For OCDS 1.0 i was used to applying the extension via http://jsonpatch.com/ format, like the one [here](https://github.com/open-contracting/implementation-and-extensions/blob/master/proposed_extensions/proposed_location/schema_usecase_2.json)

I had integrated the [json-patch](https://github.com/daveclayton/json-patch) library so that we can easily apply multiple json patches over the original 1.0 schema without changing/altering the json schema itself, this worked pretty well for us in 1.0. We used this for the location extension proposed by you.

We are now in the process of upgrading to 1.1 and re-assessing some of the official schema extensions. Do we have some new guidelines about applying extensions over the 1.1 schema ?

**Comment by timgdavies** [comment]
@mpostelnicu Yes - this was discussed in https://github.com/open-contracting/standard/issues/335 where the new approach uses [json-merge-patch](https://tools.ietf.org/html/rfc7386) rather than json-patch  - it should be fairly easy to switch in merge-patch format instead.

**Comment by mpostelnicu** [comment]
great. thanks. closing!
